name: cilicili
description: CiliCili - 一个第三方哔哩哔哩全平台客户端（参考 PiliPlus 架构）
publish_to: 'none'
version: 3.0.3+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  path_provider: ^2.1.4

flutter:
  uses-material-design: true
